#!/bin/bash

OUTFILE=../ParserTestWithFiles.cpp
TESTDIR=../test_cases

echo "#include <fstream>
#include \"gtest/gtest.h\"

#include \"../src/ErrorManager.hpp\"
#include \"../src/Parser.hpp\"

using namespace std;

namespace Meow
{" > $OUTFILE;

for file in $TESTDIR/*.pal 
do
    BASENAME=$(basename $file .pal);
    FIRSTLETTER=${BASENAME::1};
    SECONDLETTER=${BASENAME:1:1};
    if [ "$SECONDLETTER" = "f" ]
    then
        continue
    fi
    if [ "$SECONDLETTER" = "s" ]
    then
        continue
    fi
    echo "    TEST(ParserTestWithFiles, $BASENAME)
    {
        ErrorManager errorManager;
        Parser parser(&errorManager);
        int retval = parser.parseFile(\"test/test_cases/$BASENAME.pal\", \"dummyout\");
	//errorManager.printErrors();
	system(\"rm dummyout\");
	" >> $OUTFILE;


if [ "$FIRSTLETTER" = "b" ]
then
    echo "        EXPECT_NE(0, retval);
    }" >> $OUTFILE;
fi

if [ "$FIRSTLETTER" != "b" ] 
then
    echo "        EXPECT_EQ(0, retval);
    }" >> $OUTFILE;
fi

done

echo "}" >> $OUTFILE;


